### PR TITLE
Compatibility with PTL 1.6

### PR DESCRIPTION
**Pull request by krfricke**
Todos:

- [x] Check if we need `to_state_stream` / `load_state_stream` P(0)
- [x] Check multi node (P0)
- [x] Check multi GPU/multi node (P0)
- [x] Fix / change tests (P0)
- [x] Check that recent PRs are included, e.g. https://github.com/ray-project/ray_lightning/pull/156 P(0.5-1)
- [x] Check Ray client (P1)
- [x] Check fractional GPUs (P2)
- [x] DDP sharded (P2)

### CODE REVIEW

**Comment by amogkam** [comment]
Could we also merge in this PR to rename everything to strategy following the 1.6 convention.

**Comment by JiahaoYao** [comment]
Error: 
image

- [ ] enable gpu training

**Comment by JiahaoYao** [comment]
image
- [ ] multi-node gpu case, it hangs up forever.

**Comment by JiahaoYao** [comment]
`to_state_stream / load_state_stream` seems to be useful because 
the weights will not be changed
image

from this test:


https://github.com/ray-project/ray_lightning/blob/6aed848f757a03c03166c1a9bddfeea5153e7b90/ray_lightning/tests/utils.py#L241-L245

**Comment by JiahaoYao** [comment]
for the Q1: 
>  Check if we need to_state_stream / load_state_stream P(0)

Yes, we need this. On the remote task, the weights is not going to dump / load from the ckpt from the hard-disk. And ` to_state_stream / load_state_stream ` provides a elegant way to fetch and pass the weights to driver.

**Comment by JiahaoYao** [comment]
the test files used are https://github.com/JiahaoYao/ray_lightning/blob/3df599a8bb1ac917bf6352b8baef63ad64f21595/ray_lightning/tests/test_ddp_gpu.py

**Comment by JiahaoYao** [comment]
`test_ddp.py` passed

**Comment by JiahaoYao** [comment]
can close this pr @krfricke @amogkam

**Pull request closed without merging**
