### PR TITLE
LightningCLI and RayPlugin compatibility

### PR DESCRIPTION
**Pull request by mauvilsa**
Proper fix for #151 removing what #154 added.

cc @amogkam

### CODE REVIEW

**Comment by amogkam** [comment]
Thanks @mauvilsa!  

Could you add this test below this line https://github.com/ray-project/ray_lightning/blob/main/.github/workflows/test.yaml#L133 so that it gets run in CI?

Also seems like there are some lint failures. Could you run `format.sh` to fix those?

**Comment by mauvilsa** [comment]
> Thanks for the contribution @mauvilsa!
> 
> Could you add this test below this line https://github.com/ray-project/ray_lightning/blob/main/.github/workflows/test.yaml#L133 so that it gets run in CI?
> 
> Also seems like there are some lint failures. Could you run `format.sh` to fix those?

Done.

**Comment by mauvilsa** [comment]
@amogkam I addressed your comment long ago. So long that the removal of the workaround was already done in https://github.com/ray-project/ray_lightning/commit/299a776e4348050c477cbb4ecf958fb03ed64f26. However, adding the unit test still make sense.

**Comment by amogkam** [comment]
Thanks @mauvilsa and apologies for the delay! Just re-triggered the CI again.

**Review by amogkam — APPROVED** [review]

**Pull request merged**
